### ISSUE TITLE
Memory footprint of a Bucardo Kid constantly increases

### ISSUE THREAD

**Issue by jgallinari** [bucardo/bucardo#115]
Hi,
I have a simple postgreSQL master to slave replication based on Bucardo 5.4.1 with multiple herds and syncs, and I can see that the VSZ used by Bucardo Kids keeps on increasing over time.
This forces me to stop and start Bucardo regularly, which is not acceptable.

E.g.
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
postgres 115867  0.0  0.0 227912 24500 ?        S    10:58   0:05 Bucardo Kid. Sync "db2_crm_db_sync"
postgres 115873  0.0  0.0 227500 24180 ?        S    10:58   0:03 Bucardo Kid. Sync "db2_resource_db_sync"
postgres 115884  0.1  0.1 251100 47416 ?        S    10:58   0:17 Bucardo Kid. Sync "db2_rating_db_sync"
postgres 115886  0.7  0.2 275544 72120 ?        S    10:58   1:26 Bucardo Kid. Sync "db2_ods_db_sync"
postgres 115890  0.0  0.0 227772 24360 ?        S    10:58   0:03 Bucardo Kid. Sync "db2_shared_db_sync"

From log:
(115850) [Thu Jul 21 10:57:57 2016] MCP Postgres library version: 90404
(115850) [Thu Jul 21 10:57:57 2016] MCP bucardo: /usr/local/bin/bucardo
(115850) [Thu Jul 21 10:57:57 2016] MCP Bucardo.pm: /usr/local/share/perl5/Bucardo.pm
(115850) [Thu Jul 21 10:57:57 2016] MCP OS: linux  Perl: /usr/bin/perl 5.10.1
(115850) [Thu Jul 21 10:57:57 2016] MCP DBI version: 1.633  DBD::Pg version: 3.5.1 (30501) DBIx::Safe version: 1.2.5

**Comment by jgallinari** [comment]
Hi,
I tried to use the maxkicks=10 option when creating the sync in order to try to workaround this memory leak issue, but then I face a new problem after some time: the kids do not always exit properly, which leave multiple hanging kid processes in the end.

When this occurs (bad kid exit), here is what i found in the Bucardo log:

(19711) [Fri Jul 22 08:19:02 2016] CTL   stayalive: 1 checksecs: 0 kicked: 1
(19711) [Fri Jul 22 08:19:02 2016] CTL   kidsalive: 1 onetimecopy: 0 lifetimesecs: 0 (NULL) maxkicks: 10
(19707) [Fri Jul 22 08:19:02 2016] KID (db2_ods_db_sync) Kid has died, error is: CTL request Line: 5027 
(19711) [Fri Jul 22 08:19:02 2016] CTL Database "db1_db" backend PID: 19714
(19707) [Fri Jul 22 08:19:02 2016] KID (db2_ods_db_sync) Kid 19707 exiting at cleanup_kid. Sync "db2_ods_db_sync" ods_db.rt_smsc_cdr_ussd Reason: CTL request Line: 5027 
*** glibc detected *** Bucardo Kid. Sync "db2_ods_db_sync": double free or corruption (!prev): 0x0000000003637ac0 ***
*** glibc detected *** Bucardo Kid. Sync "db2_ods_db_sync": corrupted double-linked list: 0x00000000035e43d0 ***

**Comment by einhverfr** [comment]
I have run into the same problem.  The issue in my case appears to leak after doing large updates or inserts from the master to the slave.  I don't know at present if it is a circular reference problem or something else.

For now I am restarting the service every day.  Is there anything I could get in terms of diagnstics to help?

**Comment by machack666** [comment]
Hi guys, the way Bucardo is designed (with the persistent KID process) means that once it's used up the memory the only way for it to reduce it is to have the KID die and be re-spawned.  The max_kicks param is what is intended for this.

We have recently fixed a few bugs in the respawn, so curious if @jgallinari still has the issues mentioned when using HEAD.  If so, can you provide any specific details/logs?

Thanks,

David

**Comment by ewezhai** [comment]
@machack666,which values should the maxkicks be configured in default is good?Or how to get the suitable value according to my hardware's memory?

**Comment by machack666** [comment]
@ewezhai Generally the excessive memory usage would happen if there big backlogs of changes which need to be processed.  If you're using `autokick` to trigger the changes automatically, you should fairly happily processing things under normal load without issue, unless there is a huge bulk operation (say an update of an entire large table).

There is no default value for `maxkicks` (well, technically it's 0, which means it ignores it).  Since a kick would happen after every transaction with a change in autokick mode, you can set this quite high without an impact.  (Setting it very high would mean practically speaking it's basically the same thing as setting to 0, so there is no ongoing impact here.)  If set too low, it would restart the KID more frequently which could add some additional load vs the memory used if setting too high. 1000 seems like a reasonable value to set to me.

As mentioned earlier on this thread, we had fixed a few bugs related to the respawn, so if you do set this up and test this you can let us know if you run into any issues with this in the field.
