### ISSUE TITLE
Cascaded Replication 

### ISSUE THREAD

**Issue by rmadiwale** [bucardo/bucardo#122]
Is there any way where we can setup cascaded master --> slave --> slave replication using Bucardo ?
I was trying to implement mentioned scenario and were able to get data replicated from master to slave but from slave to salve it was not

**Comment by machack666** [comment]
Hi @rmadiwale,

You can set up a cascaded replication by setting up a 2-master cluster and additional targets off of the second master, basically treating the second master as read-only but not enforcing it.  (See the makedelta option for cascading changes)

An alternate approach would be to just set up a Hot Standby cluster and then then use that as the target in the Bucardo cluster; the Bucardo replication would spread to both servers in the cluster just due to PostgreSQL's native replication.

HTH,

David
