### ISSUE TITLE
Bucardo add sync will hang forever

### ISSUE THREAD

**Issue by gustavovalverde** [bucardo/bucardo#124]
I've installed bucardo a few times, but right now I'm with a weird situation in a client that I have no way to debug as the debugger says nothing: 

When I execute the **bucardo add sync ...** it will start execution and then just hang there. The output of the log (with debug activated) ends here:

`DEBUG:  parse dbdpg_p5268_15: INSERT INTO bucardo.sync (name,conflict_strategy,herd,dbs) VALUES ($1,$2,$3,$4)
LOG:  duration: 0.072 ms  parse dbdpg_p5268_15: INSERT INTO bucardo.sync (name,conflict_strategy,herd,dbs) VALUES ($1,$2,$3,$4)
DEBUG:  bind <unnamed> to dbdpg_p5268_15
LOG:  duration: 0.059 ms  bind dbdpg_p5268_15: INSERT INTO bucardo.sync (name,conflict_strategy,herd,dbs) VALUES ($1,$2,$3,$4)
DETAIL:  parameters: $1 = 'pos_sync', $2 = 'bucardo_latest', $3 = 'odoo_all_tables', $4 = 'biscuits'
DEBUG:  Starting validate_sync trigger
DEBUG:  Found insert, will call validate_sync
LOG:  Starting validate_sync for pos_sync
DEBUG:  Connecting to dbi:Pg:dbname=biscuits_bucardo;host=xx.xx.xx.xx;port=5432 as postgres inside bucardo_validate_sync for language check
`

**Comment by machack666** [comment]
Hi @gustavovalverde 

This is either one of two things:

1) inability to connect to the remote server; you can test this by checking the connection with the relevant connection parameters from the server where Bucardo is running.  This could be a timeout, say, or a firewall issue, since this would apparently not be getting an explicit connection refused.

2) blocking while trying to run the remote validate_sync; you can test this by looking to see on the source database whether the query is blocking, and if so which process is blocking it.

HTH,

David

**Comment by gustavovalverde** [comment]
After a few changes and adding the debug option in the destination database it seems to be an issue with the max_locks_per_transaction in PostgreSQL 9.3

After changing the parameter in the destination and restarting the Postgres server, all went back to normal.
