### ISSUE TITLE
Missing PlainText Module on CentOS/RHEL 8

### ISSUE THREAD

**Issue by pinkerltm** [bucardo/bucardo#217]
Bucardo is installed and running on CentOS 8. Nevertheless certain commands (for example `bucardo update dbgroup ...`) fail with the following error:

> Can't locate Pod/PlainText.pm in @INC (you may need to install the Pod::PlainText module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/local/bin/bucardo line 8638.

yum/dnf doesn't provide a package "perl-PlainText" to install and I also wasn't able to find any solution related to this certain package. How do I get this installed?

**Comment by machack666** [comment]
I don't know for CentOS 8 specifically, but in previous versions you can `yum install 'perl(Pod::PlainText)'` to install the package that corresponds to the given module, so that would be my first attempt.

Worst case you could install via CPAN or CPANM, though it would be better to use the packaged modules if they exist.

(Worst, worst case, I think that module is only used for generating docs from the internal POD documentation, so you could probably comment out the `use Pod::PlainText;` line and be fine.)

-- also, looks like you were trying to install `perl-PlainText`, not `perl-Pod-PlainText`, so I'd suspect the very first method I mentioned should work just fine.

Best,

David

**Comment by pinkerltm** [comment]
That perfectly worked and revealed that the corresponding yum package is called "perl-Pod-Parser".

Thanks for the quick response!
