### ISSUE TITLE
Partitioned tables not synced

### ISSUE THREAD

**Issue by savoir81** [bucardo/bucardo#220]
Hi, 

I created one partitioned table, partitioned by range. After that i tried to add this table to Bucardo sync but i get this message as if the table do not exists:

$ bucardo add table ident.identification herd=copying_herd
Did not find matches for the following terms:
  ident.identification

I managed, though to add partitions of this table but they are not synced to another server.

Is declarative partitioning even supported by Bucardo?

Version of PG is 12.4

Regards,
Savo

**Comment by machack666** [comment]
Hi Savo,

I would assume that we are doing some sort of filtering to specific relation type i.e., relation (=table) vs other kinds.  Since the parent partitioned table is a special type of relation (like a view or matview), it is likely this would not work directly for the parent table.

Replication of the individual partitions *should* work in theory--though I haven't tested them--assuming that you add the individual partitions in the sync and the target has the same partitioning scheme/name.  This would not work if there are different partition names or you are trying to insert into the parent table directly.

There might be potential to add explicit partitioning support, but that does not currently exist other than with the caveats above.

Best,

David

**Comment by savoir81** [comment]
Hi David, 

This is the situation. When using basic partitioning by range or similar, Bucardo on partition tables is not working. When using parent-child tables(inherit option) Bucardo is working on child tables.

Regards,
Savo

**Comment by ngekos** [comment]
Hi All,

I had same issue related partitioned tables
After I query the my pg_catalog.pg_class table and found this

```
           relname             | relkind 
--------------------------------+---------
 orders_january_2021            | r
 orders                         | p
 orders_june_2020               | r
 orders_february_2021           | r
 orders_may_2021                | r
 order_status                   | p
 orders_status_before_june_2020 | r
 orders_status_june_2020        | r
 orders_status_july_2020        | r
 orders_status_august_2020      | r
 orders_status_september_2020   | r
 orders_status_october_2020     | r
 orders_status_november_2020    | r
 orders_status_december_2020    | r
 orders_status_january_2021     | r
 orders_status_february_2021    | r
 orders_status_march_2021       | r
 orders_status_april_2021       | r
 orders_status_may_2021         | r
 orders_before_june_2020        | r
 orders_august_2020             | r
 orders_april_2021              | r
 orders_december_2020           | r
 orders_july_2020               | r
 orders_march_2021              | r
 orders_november_2020           | r
 orders_october_2020            | r
 orders_september_2020          | r
```

the partitioned tables are `orders` and `order_status`. it seems like the partitioned table has different relkind `p` instead of 'r'. btw I found this on postgres 11.

Regards,
Ghofar
