### ISSUE TITLE
bucardo logging - forwarding via rsyslog

### ISSUE THREAD

**Issue by lbabay** [bucardo/bucardo#227]
Hey all, I am having a really hard time figuring out how to change the logging level for bucardo. I would like to be able to generate some more logs for the purpose of testing out if these logs are forwarding correctly.

from my understanding, bucardo logs are not a recognized rsyslog facility, i'm using rsyslog to forward my current server logs and I was hoping that I would be able to do the same with the bucardo logs.

if anyone knows anything about this, I would love to hear back!

thank you

**Comment by jonjensen** [comment]
@lbabay Yes, Bucardo can send its logs to syslog. It is documented here:

https://bucardo.org/Bucardo/cli/

I just updated that to show the more modern bucardo command arguments instead of deprecated ones, and it shows how to change the syslog facility from the default LOCAL1.

I tested this today on the latest Bucardo sending logs to my local rsyslog server to confirm it works as expected, for example with the command:

```
bucardo restart --logdest=syslog
```

**Comment by lbabay** [comment]
thank you Jon!
