### ISSUE TITLE
Sync status is inaccurate during onetimecopy(=2)

### ISSUE THREAD

**Issue by upost** [bucardo/bucardo#233]
Installed version: 5.5.0 (from Ubuntu's package manager)

I have the following setup:

source db (postgresql 9): 75 tables, some of which have >1M rows, with active application writing to that db all the time
target db (postgresql 12): empty

I want to move everything to the target db and sync without service interruption. (Later I want to switch the application to the new database.)

I have setup the sync successfully, set onetimecopy=2 and from the postgres logs, I see that Bucardo is doing something.

BUT I cannot properly monitor the progress with bucardo status [syncname]. Actually the status shown is something like "current state: DELETE public.tablename..." while it is actually doing a COPY from STDIN (seen in pg_activity table). Also status shows "Last Error: Ended", and "Rows deleted/inserted: 11/18", this is really misleasing.

I suggest that, while onetimecopy is running, at least display this information and how many tables already have been copied. Estimation of remaining time is nice to have.

Thank you for this great tool!

**Comment by hasegeli** [comment]
Thanks for reporting an issue.

I tried reproducing this on the current HEAD.  Here is what I got for `bucardo status`:

```
======================================================================
Last good                : Apr 26, 2021 17:51:12 (time to run: 5s)
Rows deleted/inserted    : 0 / 1,000,002
Sync name                : nopk
Current state            : Good
Source relgroup/database : nopk / db1
Tables in sync           : 2
Status                   : Active
Check time               : None
Overdue time             : 00:00:00
Expired time             : 00:00:00
Stayalive/Kidsalive      : No / No
Rebuild index            : No
Autokick                 : Yes
Onetimecopy              : Yes
Post-copy analyze        : Yes
Last error:              :
======================================================================
```

The output may have changes since version 5.5.

The latest version is 5.6.  We are about to release a new version.  There are pending changes related to the fullcopy feature.  I suggest upgrading once it is released.

That said, I am not very confident about the "status" command outputting up-to-date information at all times, I just couldn't reproduce it with the information you have give.  Please feel free to report back with a reproducible test case against the latest version.
