### ISSUE TITLE
Please raise up Cloudflare Firewall limitations

### ISSUE THREAD

**Issue by davendu** [bucardo/bucardo#254]
WHen I was trying to download Bucardo to my server via the address provided on the [homepage](https://bucardo.org/Bucardo/), the following error returned:

```
$ curl https://bucardo.org/downloads/Bucardo-5.6.0.tar.gz   
error code: 1020
```

Maybe a more flexible firewall rule would be helpful for users to download the tarball directly.

**Comment by jonjensen** [comment]
Sorry for the hassle. I sometimes have felt it myself.

We don't really have "flexibility" in the firewall that wouldn't leave access wide open. Cloudflare uses its own heuristics to decide when to allow or deny traffic. We aren't going to remove the Cloudflare firewall because there is an amazing amount of abuse that gets thrown at our server that they stop.

You may want to try using a User-Agent request header other than curl:

```sh
curl -A 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0' https://bucardo.org/downloads/Bucardo-5.6.0.tar.gz
```

That often gets around simple bot blocking.

**Comment by davendu** [comment]
Sadly, Cloudflare may have their own decisions, and I still got `1020` even if carrying cookies & other request headers.

Anyway, since Bucardo is small, `scp` from my laptop is enough. Still, thanks for your advice ;)

**Comment by jonjensen** [comment]
@davendu Would you mind trying your curl download from that same location again if you can? We found some settings to loosen things up in Cloudflare without disabling abuse blocking, and I'm curious if it works for you now.

**Comment by davendu** [comment]
@jonjensen still got `1020`, sadly :(
